### ISSUE TITLE
There are no text limits on the free input fields

### ISSUE THREAD

**Issue by kauffmanes** [kauffmanes/zuni-data-app#1]
There are no text limits on the free input fields, which means that you can type more characters than the database allows.

**Comment by samfee** [comment]
I believe the database limit is 500 characters. But that is too much for anything but the notes section. We should limit Site Name to 50 characters, And all the others to 5 since they are cm measurements. We'll leave Notes at 500. Does that sound like a good plan to you?

**Comment by kauffmanes** [comment]
Site name has been limited to 50 and textarea to 500. Not too worried about the measurement limits

**Comment by kauffmanes** [comment]
Can you re-test and close?

**Comment by samfee** [comment]
Yep, I think we are good - especially now that we've updated the db to match. Won't be able to test for a couple days, but as soon as I can, I will!
