### ISSUE TITLE
Averages Are Not Working

### ISSUE THREAD

**Issue by samfee** [kauffmanes/zuni-data-app#10]
I know you had these working earlier - but they are not working now. Also none of the values (the original entries and the averages) are writing to the database.

**Comment by kauffmanes** [comment]
We had decided to only store the average I believe. Has this changed?

**Comment by samfee** [comment]
I can't remember if it's changed or not - I'm sorry. It's been so long since I talked to him I don't remember. I can hunt through my emails again? 

But I'm talking about the boxes we have in the app. Width of Indentation, Depth of Indentation, and Coil width. I thought that it was working previously as putting a value in that last box? It seems that the columns are already created in the database, so we may as well write that values to it. Also, they have been tracking that so at this last stage, I don't think we should change it.

**Comment by kauffmanes** [comment]
Please re-test. For the record, my solution is not great, but it is built based on the assumption we didn't care about individual measurements. we can go back and fix this if needed/we have time. Let me know if you see anything weird.

**Comment by samfee** [comment]
This seems to be working fine - both in the app and with the resulting database entries. I'm closing...
