### ISSUE TITLE
Database Revisions

### ISSUE THREAD

**Issue by samfee** [kauffmanes/zuni-data-app#11]
Here are the changes we can make to the database. We should revise the script to match:

1) Remove columns Prov, Spec, and ID.
2) The Part column should be re-named Portion
3) IndPerCalc should divide the value in IndPerCT by 9
4) Remove the Oblit calc column
5) The Rim Dia column should be renamed Rim Rad

** I don't remember how to do number 3. I've removed/renamed the columns in the other items as reflected in the script below. Could you review my syntax before I run it?

**Comment by samfee** [comment]
This is the revised SQL script I'm thinking of for the database assuming the above changes. Can you take a look and let me know if you think it's correct:

USE samfeeco_cibola;

DROP TABLE IF EXISTS tbl_all_finds;

CREATE TABLE tbl_all_finds (
    UNQID INT NOT NULL AUTO_INCREMENT,
    Site VARCHAR(21) NOT NULL,
    Clay VARCHAR(2),
    Portion INT,
    `Type` VARCHAR(2),
    `Indt Type` VARCHAR(1),
    Direc VARCHAR(1),
    `Indt Algn` VARCHAR(1),
    Elab VARCHAR(2),
    Form INT,
    Smg INT,
    `Int Surf` VARCHAR(1),
    Soot VARCHAR(1),
    Thick VARCHAR(3),
    `IndWidth 1` VARCHAR(3),
    `IndWidth 2` VARCHAR(3),
    `IndWidth 3` VARCHAR(3),
    `IndWidth AVG` VARCHAR(3),
    `Depth 1` VARCHAR(3),
    `Depth 2` VARCHAR(3),
    `Depth 3` VARCHAR(3),
    `Depth AVG` VARCHAR(3),
    `Coils 1` VARCHAR(3),
    `Coils 2` VARCHAR(3),
    `Coils 3` VARCHAR(3),
    `Coils AVG` VARCHAR(3),
    `IndPer CT` VARCHAR(3),
    `IndPer Calc` VARCHAR(3),
    `Oblit P` VARCHAR(2),
    `Oblit O` VARCHAR(2),
    `Rim Rad` VARCHAR(3),
    `Dist to coils` VARCHAR(3),
    `Rim Form` VARCHAR(2),
    `Coil Direc` VARCHAR(1),
    `Date` DATETIME NOT NULL DEFAULT NOW(),
	dateCollected VARCHAR(25) NOT NULL,
    `Notes` VARCHAR(500),
    
    CONSTRAINT pk_unqid PRIMARY KEY (UNQID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

**Comment by kauffmanes** [comment]
Okay, I added vessel portion to match "Portion" column

**Comment by kauffmanes** [comment]
Added Rim Rad - building!

**Comment by kauffmanes** [comment]
Please retest this @samfee

**Comment by samfee** [comment]
Testing complete - everything seems to work for these five columns. Closing this issue.
