### ISSUE TITLE
App Fields Not Mapping

### ISSUE THREAD

**Issue by samfee** [kauffmanes/zuni-data-app#12]
Here is a list of fields in the app that are not mapping the database (app field/database column):

Vessel Portion / Part [to be changed to Portion]
Width of Indentations / 1, 2, 3, AVG
Depth of Indentations / 1, 2, 3, AVG
Coil Width / 1, 2, 3, AVG
Rim Radius / Rim Dia [to be changed to Rim Rad]

**Comment by kauffmanes** [comment]
Please re-test:
1. vessel portion
2. width indentation measurements
3. depth indentation measurements
4. coil width measurements
5. rim radius

**Comment by samfee** [comment]
All of these are tested and appear to be working now.
