### ISSUE TITLE
99 Values not mapping

### ISSUE THREAD

**Issue by samfee** [kauffmanes/zuni-data-app#15]
For Indt Type and INT Surf as per my email. App is recording as ‘9’ and not ’99’.

**Comment by kauffmanes** [comment]
It is posting as 99, so I believe this is on your DB side. Do you have it mapped to one character/digit?

**Comment by kauffmanes** [comment]
Column size is limited to one character. 99 is becoming 9.
![screen shot 2017-06-01 at 6 48 06 pm](https://cloud.githubusercontent.com/assets/6700354/26704215/9c11e1f4-46fb-11e7-9e12-a61681a407b2.png)

**Comment by samfee** [comment]
I'm looking for the database script, its in an old issue...grr. I probably shouldn't have closed it. I''ll go look!

**Comment by samfee** [comment]
This was definitely the problem. I fixed those two columns and created a new issue with the updated script. I'm assigning it to you just for a quick review, and I'm closing this issue out.
