### ISSUE TITLE
Database Script

### ISSUE THREAD

**Issue by samfee** [kauffmanes/zuni-data-app#16]
I just made a new issue with this script so we can find it easily. Here's the current script (I believe) expecting any modifications Em has made in the last week. I made the two corrections to the two columns that were limited to one character. So please let me know if you see any errors:

USE samfeeco_cibola;

DROP TABLE IF EXISTS tbl_all_finds;

CREATE TABLE tbl_all_finds (
UNQID INT NOT NULL AUTO_INCREMENT,
Site VARCHAR(21) NOT NULL,
Clay VARCHAR(2),
Portion INT,
Type VARCHAR(2),
Indt Type VARCHAR(2),
Direc VARCHAR(1),
Indt Algn VARCHAR(1),
Elab VARCHAR(2),
Form INT,
Smg INT,
Int Surf VARCHAR(2),
Soot VARCHAR(1),
Thick VARCHAR(3),
IndWidth 1 VARCHAR(3),
IndWidth 2 VARCHAR(3),
IndWidth 3 VARCHAR(3),
IndWidth AVG VARCHAR(3),
Depth 1 VARCHAR(3),
Depth 2 VARCHAR(3),
Depth 3 VARCHAR(3),
Depth AVG VARCHAR(3),
Coils 1 VARCHAR(3),
Coils 2 VARCHAR(3),
Coils 3 VARCHAR(3),
Coils AVG VARCHAR(3),
IndPer CT VARCHAR(3),
IndPer Calc VARCHAR(3),
Oblit P VARCHAR(2),
Oblit O VARCHAR(2),
Rim Rad VARCHAR(3),
Dist to coils VARCHAR(3),
Rim Form VARCHAR(2),
Coil Direc VARCHAR(1),
Date DATETIME NOT NULL DEFAULT NOW(),
dateCollected VARCHAR(25) NOT NULL,
Notes VARCHAR(500),

CONSTRAINT pk_unqid PRIMARY KEY (UNQID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by kauffmanes** [comment]
`Site VARCHAR(21) NOT NULL`
You had me limit this one in the UI to 50... do you want 21 or 50? The UI shouldn't accept more than the DB

**Comment by kauffmanes** [comment]
The rest looks good though! Gonna do some tests

**Comment by samfee** [comment]
You are right. I'll change this to 50 and repost here:

USE samfeeco_cibola;

DROP TABLE IF EXISTS tbl_all_finds;

CREATE TABLE tbl_all_finds (
UNQID INT NOT NULL AUTO_INCREMENT,
Site VARCHAR(50) NOT NULL,
Clay VARCHAR(2),
Portion INT,
Type VARCHAR(2),
Indt Type VARCHAR(2),
Direc VARCHAR(1),
Indt Algn VARCHAR(1),
Elab VARCHAR(2),
Form INT,
Smg INT,
Int Surf VARCHAR(2),
Soot VARCHAR(1),
Thick VARCHAR(3),
IndWidth 1 VARCHAR(3),
IndWidth 2 VARCHAR(3),
IndWidth 3 VARCHAR(3),
IndWidth AVG VARCHAR(3),
Depth 1 VARCHAR(3),
Depth 2 VARCHAR(3),
Depth 3 VARCHAR(3),
Depth AVG VARCHAR(3),
Coils 1 VARCHAR(3),
Coils 2 VARCHAR(3),
Coils 3 VARCHAR(3),
Coils AVG VARCHAR(3),
IndPer CT VARCHAR(3),
IndPer Calc VARCHAR(3),
Oblit P VARCHAR(2),
Oblit O VARCHAR(2),
Rim Rad VARCHAR(3),
Dist to coils VARCHAR(3),
Rim Form VARCHAR(2),
Coil Direc VARCHAR(1),
Date DATETIME NOT NULL DEFAULT NOW(),
dateCollected VARCHAR(25) NOT NULL,
Notes VARCHAR(500),

CONSTRAINT pk_unqid PRIMARY KEY (UNQID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by samfee** [comment]
UPDATED script with annoying ticks included:

USE samfeeco_cibola;

DROP TABLE IF EXISTS tbl_all_finds;

CREATE TABLE tbl_all_finds (
UNQID INT NOT NULL AUTO_INCREMENT,
Site VARCHAR(21) NOT NULL,
Clay VARCHAR(2),
Portion INT,
Type VARCHAR(2),
`Indt Type` VARCHAR(2),
Direc VARCHAR(1),
`Indt Algn` VARCHAR(1),
Elab VARCHAR(2),
Form INT,
Smg INT,
`Int Surf` VARCHAR(2),
Soot VARCHAR(1),
Thick VARCHAR(3),
`IndWidth 1` VARCHAR(3),
`IndWidth 2` VARCHAR(3),
`IndWidth 3` VARCHAR(3),
`IndWidth AVG` VARCHAR(3),
`Depth 1` VARCHAR(3),
`Depth 2` VARCHAR(3),
`Depth 3` VARCHAR(3),
`Depth AVG` VARCHAR(3),
`Coils 1` VARCHAR(3),
`Coils 2` VARCHAR(3),
`Coils 3` VARCHAR(3),
`Coils AVG` VARCHAR(3),
`IndPer CT` VARCHAR(3),
`IndPer Calc` VARCHAR(3),
`Oblit P` VARCHAR(2),
`Oblit O` VARCHAR(2),
`Rim Rad` VARCHAR(3),
`Dist to coils` VARCHAR(3),
`Rim Form` VARCHAR(2),
`Coil Direc` VARCHAR(1),
Date DATETIME NOT NULL DEFAULT NOW(),
dateCollected VARCHAR(25) NOT NULL,
Notes VARCHAR(500),

CONSTRAINT pk_unqid PRIMARY KEY (UNQID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by kauffmanes** [comment]
What is Oblit O? I only have Oblit P

**Comment by kauffmanes** [comment]
From @samfee - Oblit O is an existing field that we kept - no new data is writing to it as of now.
