### ISSUE TITLE
Submit from Keyboard

### ISSUE THREAD

**Issue by samfee** [kauffmanes/zuni-data-app#4]
When the keyboard is active, you can submit the form just by hitting return. Yikes!!

**Comment by kauffmanes** [comment]
I removed the submit on the form element and move it to a click event on the submit button. Now you can only submit when clicking the submit button. No accidentally keyboard clicks.

**Comment by samfee** [comment]
Perfect. I'm just going to close this one. I can't imagine this solution not solving the problems.
