### ISSUE TITLE
Varying Styles

### ISSUE THREAD

**Issue by samfee** [kauffmanes/zuni-data-app#5]
Pop up menus (for selection options) have differing styles. Some are specified, others default to system (i.e. Safari) styles.

**Comment by kauffmanes** [comment]
Which ones are different?

**Comment by samfee** [comment]
Checking now...These default to the standard system styles:

Vessel Form
Smudging
Sooting
Rim - Rim Form
Basal - Direction of coils.

**Comment by kauffmanes** [comment]
This is default behavior of the browser.
