### ISSUE TITLE
Type of Indentations

### ISSUE THREAD

**Issue by samfee** [kauffmanes/zuni-data-app#6]
Is missing option 2. We'll have to go back to the original docs to see what it should have been...

Why aren't there emojis in Git?

**Comment by kauffmanes** [comment]
There are... 👎 

This is on the original docs. Perhaps that 3 is just supposed to be a 2?

![screen shot 2017-05-23 at 10 38 09 pm](https://cloud.githubusercontent.com/assets/6700354/26384623/9d63b572-4008-11e7-817d-91fd7061cef7.png)

**Comment by samfee** [comment]
Duh. I even see the button for the emojis now...

Yes - let's just change 3 to 2 and hope that's OK. I'll confirm with Matt.

**Comment by samfee** [comment]
OK - heard back on this one. 3 is actually the CORRECT value because 2 was used in earlier experimental data collection and needs to be retained (even though it isn't being used). 

So, with no change required, I am closing this one out!
