### ISSUE TITLE
Database Values

### ISSUE THREAD

**Issue by samfee** [kauffmanes/zuni-data-app#7]
Some content is being written to the database not as the number (as it should be) but as a bracket "[" 

Wha???

Let me know if you want me to track down specifics.

**Comment by kauffmanes** [comment]
Ha - this was a tricky one. I am parsing the form data to format it for the POST, and I was check to make sure the value exists... but when you've chose "indeterminate", the value is 0, which evaluates to false, which was making the formatting function failed. I've updated it to check for truthy OR the value is 0.

**Comment by samfee** [comment]
Oh this IS interesting! That’s good. Who knows how long it would have taken me to remember that!! Haha! Nice catch.

So should we close this one now or keep looking for other values. I'll tests everything that is not a zero today; but I'm thinking it was all 0=false...

**Comment by samfee** [comment]
I've tested this thoroughly and I think we've got it. Good work Em! I'm closing this since it seems resolved - it anything crops up I'll make a new issue.
